version: '3'

volumes:
  pg_data_kitty:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env.example
    volumes:
      - pg_data_kitty:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env.example
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    build: ./nginx/
    env_file: .env.example
    ports:
      - ${NGINX_PORT}:${HOST_PORT}
    depends_on:
      - backend
    volumes:
      - static:/static
      - media:/app/media